name: Plantalk Services CI

on:
  push:
    branches:
      - services

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install, build, and test
      run: |
        cd ./services
        npm ci
        cd ..
        ./node_modules/.bin/firebase deploy --project plantalk-test2704 --debug --only functions --token "$FIREBASE_TOKEN"
      env:
        CI: true